var defaults = {
    "autoupdate": true,
    "checkTime": 5,
    "useAutoLogin": false,
    "openInbox": false,
    "focusInbox": true,
    "openNotification": true,
    "playSound": true,
    "sound": "chrome-extension://__MSG_@@extension_id__/sounds/splat.wav",
    "noMsgLook": "0",
    "noMsgText": "No messages",
    "preventMultiInbox": true,
    
    "customLook": true,
    "bkgColor": "#728776",
    "textColor": "#bad4c1",
    "newTextColor": "#ffffff",
    
    "followNotices": true,
    "followActivityMsg": true,
    "followReplies": true,
    "followNotes": true,
    "followJournals": true,
    "followComments": true,
    "followDeviations": true,
    "followPolls": true,
    "followContest": true,
    "followNews": true,
    "followCritiques": true,
    "followCorrespondence": true,
    "followSupport": true,
    "followBulletin": true,
    "followForum": true,
    "followWatchedActivity": true
};